wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.17.0
    framework: huggingface
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1716057790
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 11
      - 12
      - 49
      - 55
      3:
      - 2
      - 23
      4: 3.10.12
      5: 0.17.0
      8:
      - 1
      - 5
      - 12
      13: linux-x86_64
